/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangToolsRouteImport } from './routes/$lang/tools'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangBlogRouteImport } from './routes/$lang/blog'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangToolsSlugRouteImport } from './routes/$lang/tools.$slug'
import { Route as LangConsole7k9m2pRouteImport } from './routes/$lang/console.7k9m2p'
import { Route as LangBlogSlugRouteImport } from './routes/$lang/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangToolsRoute = LangToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBlogRoute = LangBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangToolsSlugRoute = LangToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangToolsRoute,
} as any)
const LangConsole7k9m2pRoute = LangConsole7k9m2pRouteImport.update({
  id: '/console/7k9m2p',
  path: '/console/7k9m2p',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/tools': typeof LangToolsRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/console/7k9m2p': typeof LangConsole7k9m2pRoute
  '/$lang/tools/$slug': typeof LangToolsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/tools': typeof LangToolsRouteWithChildren
  '/$lang': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/console/7k9m2p': typeof LangConsole7k9m2pRoute
  '/$lang/tools/$slug': typeof LangToolsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRouteWithChildren
  '/$lang/contact': typeof LangContactRoute
  '/$lang/tools': typeof LangToolsRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/console/7k9m2p': typeof LangConsole7k9m2pRoute
  '/$lang/tools/$slug': typeof LangToolsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/tools'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/console/7k9m2p'
    | '/$lang/tools/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/tools'
    | '/$lang'
    | '/$lang/blog/$slug'
    | '/$lang/console/7k9m2p'
    | '/$lang/tools/$slug'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/tools'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/console/7k9m2p'
    | '/$lang/tools/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/tools': {
      id: '/$lang/tools'
      path: '/tools'
      fullPath: '/$lang/tools'
      preLoaderRoute: typeof LangToolsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/blog': {
      id: '/$lang/blog'
      path: '/blog'
      fullPath: '/$lang/blog'
      preLoaderRoute: typeof LangBlogRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/tools/$slug': {
      id: '/$lang/tools/$slug'
      path: '/$slug'
      fullPath: '/$lang/tools/$slug'
      preLoaderRoute: typeof LangToolsSlugRouteImport
      parentRoute: typeof LangToolsRoute
    }
    '/$lang/console/7k9m2p': {
      id: '/$lang/console/7k9m2p'
      path: '/console/7k9m2p'
      fullPath: '/$lang/console/7k9m2p'
      preLoaderRoute: typeof LangConsole7k9m2pRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangBlogRoute
    }
  }
}

interface LangBlogRouteChildren {
  LangBlogSlugRoute: typeof LangBlogSlugRoute
}

const LangBlogRouteChildren: LangBlogRouteChildren = {
  LangBlogSlugRoute: LangBlogSlugRoute,
}

const LangBlogRouteWithChildren = LangBlogRoute._addFileChildren(
  LangBlogRouteChildren,
)

interface LangToolsRouteChildren {
  LangToolsSlugRoute: typeof LangToolsSlugRoute
}

const LangToolsRouteChildren: LangToolsRouteChildren = {
  LangToolsSlugRoute: LangToolsSlugRoute,
}

const LangToolsRouteWithChildren = LangToolsRoute._addFileChildren(
  LangToolsRouteChildren,
)

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangBlogRoute: typeof LangBlogRouteWithChildren
  LangContactRoute: typeof LangContactRoute
  LangToolsRoute: typeof LangToolsRouteWithChildren
  LangIndexRoute: typeof LangIndexRoute
  LangConsole7k9m2pRoute: typeof LangConsole7k9m2pRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangBlogRoute: LangBlogRouteWithChildren,
  LangContactRoute: LangContactRoute,
  LangToolsRoute: LangToolsRouteWithChildren,
  LangIndexRoute: LangIndexRoute,
  LangConsole7k9m2pRoute: LangConsole7k9m2pRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
