/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangToolsRouteImport } from './routes/$lang/tools'
import { Route as LangPricingRouteImport } from './routes/$lang/pricing'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangBlogRouteImport } from './routes/$lang/blog'
import { Route as LangAboutRouteImport } from './routes/$lang/about'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangToolsRoute = LangToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPricingRoute = LangPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBlogRoute = LangBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/pricing': typeof LangPricingRoute
  '/$lang/tools': typeof LangToolsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/pricing': typeof LangPricingRoute
  '/$lang/tools': typeof LangToolsRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/blog': typeof LangBlogRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/pricing': typeof LangPricingRoute
  '/$lang/tools': typeof LangToolsRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/pricing'
    | '/$lang/tools'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/pricing'
    | '/$lang/tools'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/blog'
    | '/$lang/contact'
    | '/$lang/pricing'
    | '/$lang/tools'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/tools': {
      id: '/$lang/tools'
      path: '/tools'
      fullPath: '/$lang/tools'
      preLoaderRoute: typeof LangToolsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/pricing': {
      id: '/$lang/pricing'
      path: '/pricing'
      fullPath: '/$lang/pricing'
      preLoaderRoute: typeof LangPricingRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/blog': {
      id: '/$lang/blog'
      path: '/blog'
      fullPath: '/$lang/blog'
      preLoaderRoute: typeof LangBlogRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangBlogRoute: typeof LangBlogRoute
  LangContactRoute: typeof LangContactRoute
  LangPricingRoute: typeof LangPricingRoute
  LangToolsRoute: typeof LangToolsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangBlogRoute: LangBlogRoute,
  LangContactRoute: LangContactRoute,
  LangPricingRoute: LangPricingRoute,
  LangToolsRoute: LangToolsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
